[package]
name = "raytracer"
version = "0.1.0"
authors = ["Zach Moazeni <zach.moazeni@gmail.com>"]
edition = "2018"

[lib]
name = "raytracer"
path = "src/lib.rs"

[[example]]
name = "cannon"
path = "example/cannon.rs"

[dependencies]
